-- Nothing Pakistan: fresh Supabase project bootstrap
-- Checked against the application models on 2026-07-26.
--
-- Run this file once in Supabase Dashboard > SQL Editor on a NEW/EMPTY project.
-- It creates the enum types, tables, constraints, indexes, RLS, and Data API grants.
-- It does not insert catalog/customer/order data and it does not delete anything.
--
-- Safety: the preflight block aborts the entire transaction if any application
-- table or enum already exists. For an existing database, use a reviewed
-- migration instead of this bootstrap.

begin;

set local lock_timeout = '5s';
set local statement_timeout = '60s';

-- ---------------------------------------------------------------------------
-- Preflight: refuse to mix this fresh-project bootstrap with an existing schema
-- ---------------------------------------------------------------------------

do $$
declare
  object_name text;
  application_tables constant text[] := array[
    'blogs',
    'categories',
    'category_relations',
    'colors',
    'faqs',
    'images',
    'mobiles',
    'orders',
    'product_feature_sections',
    'product_feature_slides',
    'product_mobiles',
    'products',
    'reviews',
    'spec_group_items',
    'spec_groups',
    'users'
  ];
  application_types constant text[] := array[
    'blog_content_type',
    'order_status_enum',
    'payment_status_enum',
    'product_type_enum',
    'related_type_enum'
  ];
begin
  foreach object_name in array application_tables loop
    if to_regclass(format('public.%I', object_name)) is not null then
      raise exception
        'Bootstrap stopped: public.% already exists. Use a migration for an existing database.',
        object_name;
    end if;
  end loop;

  foreach object_name in array application_types loop
    if exists (
      select 1
      from pg_type as t
      join pg_namespace as n on n.oid = t.typnamespace
      where n.nspname = 'public'
        and t.typname = object_name
    ) then
      raise exception
        'Bootstrap stopped: enum public.% already exists. Use a migration for an existing database.',
        object_name;
    end if;
  end loop;
end
$$;

-- ---------------------------------------------------------------------------
-- Enum types (mirrors lib/models/supabase-enums.ts)
-- ---------------------------------------------------------------------------

create type public.related_type_enum as enum (
  'product',
  'blog',
  'review',
  'category',
  'mobile',
  'detail_mobile',
  'detail_product'
);

create type public.payment_status_enum as enum (
  'pending',
  'paid',
  'failed'
);

create type public.order_status_enum as enum (
  'pending',
  'processing',
  'shipped',
  'delivered',
  'cancelled'
);

create type public.product_type_enum as enum (
  'charger',
  'data_cable',
  'protector',
  'earbuds',
  'headphones',
  'watch',
  'covers',
  'screen_protector'
);

create type public.blog_content_type as enum (
  'blog',
  'guide',
  'comparison',
  'news',
  'review',
  'faq'
);

-- ---------------------------------------------------------------------------
-- Core tables
--
-- Legacy identifiers such as "Price", "Address", "Postal Code", "City", and
-- piority are intentionally preserved because the current application queries
-- those exact column names.
-- ---------------------------------------------------------------------------

create table public.colors (
  id integer generated by default as identity primary key,
  name character varying(50) not null,
  hex_code character varying(7),
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now()
);

create table public.categories (
  id integer generated by default as identity primary key,
  name character varying(255) not null,
  slug character varying(255) not null unique,
  meta_title character varying(255),
  meta_description text,
  seo_keywords text,
  canonical_url text,
  schema_json jsonb,
  seo_description_long text,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  parent_id integer,
  constraint categories_parent_id_fkey
    foreign key (parent_id)
    references public.categories (id)
    on delete set null
);

create table public.products (
  id integer generated by default as identity primary key,
  name character varying(255) not null,
  slug character varying(255) not null unique,
  description text,
  short_description text,
  meta_title character varying(255),
  meta_description text,
  seo_keywords text,
  canonical_url text,
  schema_json jsonb,
  seo_description_long text,
  image_alt_text text,
  price numeric(10, 2),
  stock_quantity integer default 0,
  main_color_id integer,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  product_type public.product_type_enum,
  comparison_family text generated always as (
    case product_type
      when 'earbuds'::public.product_type_enum then 'earbuds'
      when 'headphones'::public.product_type_enum then 'headphones'
      when 'watch'::public.product_type_enum then 'watch'
      when 'charger'::public.product_type_enum then 'charger'
      else null
    end
  ) stored,
  constraint products_comparison_family_check
    check (
      comparison_family is null
      or comparison_family in ('earbuds', 'headphones', 'watch', 'charger')
    ),
  constraint products_main_color_id_fkey
    foreign key (main_color_id)
    references public.colors (id)
);

create table public.mobiles (
  id integer generated by default as identity primary key,
  name character varying(255) not null,
  slug character varying(255) not null unique,
  description text,
  meta_title character varying(255),
  meta_description text,
  seo_keywords text,
  canonical_url text,
  schema_json jsonb,
  seo_description_long text,
  image_alt_text text,
  release_date date,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  "Price" integer,
  pta_tax bigint,
  non_pta_price bigint,
  piority integer,
  original_price integer,
  warranty smallint not null default 1,
  comparison_family text
    generated always as ('mobile'::text) stored,
  constraint mobiles_comparison_family_check
    check (comparison_family = 'mobile'),
  constraint mobiles_warranty_check
    check (warranty in (1, 2)),
  constraint mobiles_original_price_check
    check (
      original_price is null
      or "Price" is null
      or original_price >= "Price"
    )
);

create table public.users (
  id integer generated by default as identity primary key,
  name character varying(255) not null,
  phone character varying(20),
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  "Address" text,
  "Postal Code" text,
  "City" text
);

create table public.blogs (
  id integer generated by default as identity primary key,
  title character varying(255) not null,
  slug character varying(255) not null unique,
  content text not null,
  meta_title character varying(255),
  meta_description text,
  excerpt text,
  focus_keyword character varying(255),
  category character varying(100),
  tags text[],
  author character varying(255),
  author_type character varying(50),
  content_type public.blog_content_type not null default 'blog',
  reading_time integer,
  featured_image_id integer,
  is_published boolean default false,
  published_at timestamp without time zone,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now()
);

-- ---------------------------------------------------------------------------
-- Relationship and content-detail tables
-- ---------------------------------------------------------------------------

create table public.category_relations (
  id integer generated by default as identity primary key,
  category_id integer not null,
  related_type public.related_type_enum not null,
  related_id integer not null,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  constraint category_relations_category_id_fkey
    foreign key (category_id)
    references public.categories (id)
    on delete cascade,
  constraint category_relations_unique
    unique (category_id, related_type, related_id)
);

create table public.images (
  id integer generated by default as identity primary key,
  related_type public.related_type_enum not null,
  related_id integer not null,
  color_id integer,
  url character varying(500) not null,
  alt_text character varying(255),
  created_at timestamp without time zone default now(),
  title character varying(160),
  caption text,
  file_name character varying(255),
  slug character varying(200),
  sort_order integer not null default 0,
  updated_at timestamp without time zone not null default now(),
  constraint images_color_id_fkey
    foreign key (color_id)
    references public.colors (id),
  constraint images_related_slug_unique
    unique (related_type, related_id, slug)
);

create table public.faqs (
  id integer generated by default as identity primary key,
  related_type public.related_type_enum not null,
  related_id integer not null,
  question text not null,
  answer text not null,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now()
);

create table public.reviews (
  id integer generated by default as identity primary key,
  related_type public.related_type_enum,
  related_id integer,
  user_name character varying(255) not null,
  rating integer,
  comment text,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  constraint reviews_rating_check
    check (rating between 1 and 5)
);

create table public.product_mobiles (
  id integer generated by default as identity primary key,
  product_id integer,
  mobile_id integer,
  created_at timestamp without time zone default now(),
  constraint product_mobiles_product_id_fkey
    foreign key (product_id)
    references public.products (id)
    on delete cascade,
  constraint product_mobiles_mobile_id_fkey
    foreign key (mobile_id)
    references public.mobiles (id)
    on delete cascade
);

create table public.orders (
  id integer generated by default as identity primary key,
  user_id integer,
  items jsonb not null,
  total_price numeric(10, 2),
  shipping_address text,
  billing_address text,
  payment_status public.payment_status_enum default 'pending',
  order_status public.order_status_enum default 'pending',
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  constraint orders_user_id_fkey
    foreign key (user_id)
    references public.users (id)
);

create table public.spec_groups (
  id integer generated by default as identity primary key,
  related_type public.related_type_enum not null,
  related_id integer not null,
  title text not null,
  subtitle text,
  icon_key text,
  media_url text,
  media_alt text,
  media_type text default 'image',
  media_position text default 'top',
  default_open boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now()
);

create table public.spec_group_items (
  id integer generated by default as identity primary key,
  spec_group_id integer not null,
  section text,
  label text not null,
  value text not null,
  sort_order integer not null default 0,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  constraint spec_group_items_spec_group_id_fkey
    foreign key (spec_group_id)
    references public.spec_groups (id)
    on delete cascade
);

create table public.product_feature_sections (
  id integer generated by default as identity primary key,
  related_type public.related_type_enum not null,
  related_id integer not null,
  source_key text,
  feature_key text not null,
  feature_title text not null,
  feature_version text,
  title text not null,
  display_context text not null default 'mobile',
  cover_image_url text,
  cover_video_playback_id text,
  cover_video_url text,
  cover_thumbnail_url text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  constraint product_feature_sections_display_context_check
    check (display_context in ('mobile', 'desktop', 'all'))
);

create table public.product_feature_slides (
  id integer generated by default as identity primary key,
  product_feature_section_id integer not null,
  source_key text,
  title text not null,
  body text,
  media_type text not null default 'image',
  image_url text,
  video_playback_id text,
  video_url text,
  thumbnail_url text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  constraint product_feature_slides_section_id_fkey
    foreign key (product_feature_section_id)
    references public.product_feature_sections (id)
    on delete cascade,
  constraint product_feature_slides_media_type_check
    check (media_type in ('image', 'video'))
);

-- ---------------------------------------------------------------------------
-- Indexes for current application filters, ordering, joins, and JSONB/search
-- ---------------------------------------------------------------------------

create index categories_parent_id_idx
  on public.categories (parent_id);
create index categories_seo_keywords_idx
  on public.categories using gin (
    to_tsvector('english', coalesce(seo_keywords, ''))
  );
create index categories_canonical_url_idx
  on public.categories (canonical_url);
create index categories_schema_json_idx
  on public.categories using gin (schema_json);

create index products_main_color_id_idx
  on public.products (main_color_id);
create index products_seo_keywords_idx
  on public.products using gin (
    to_tsvector('english', coalesce(seo_keywords, ''))
  );
create index products_canonical_url_idx
  on public.products (canonical_url);
create index products_schema_json_idx
  on public.products using gin (schema_json);
create index products_comparison_family_name_idx
  on public.products (comparison_family, name)
  where comparison_family is not null;

create index mobiles_seo_keywords_idx
  on public.mobiles using gin (
    to_tsvector('english', coalesce(seo_keywords, ''))
  );
create index mobiles_canonical_url_idx
  on public.mobiles (canonical_url);
create index mobiles_schema_json_idx
  on public.mobiles using gin (schema_json);
create index mobiles_priority_name_idx
  on public.mobiles (piority, name);
create index mobiles_comparison_family_priority_name_idx
  on public.mobiles (comparison_family, piority, name);

create index blogs_published_idx
  on public.blogs (is_published, published_at desc, updated_at desc);

create index category_relations_related_idx
  on public.category_relations (related_type, related_id);

create index images_color_id_idx
  on public.images (color_id);
create index images_related_sort_idx
  on public.images (related_type, related_id, sort_order);
create index images_slug_idx
  on public.images (slug);

create index faqs_related_idx
  on public.faqs (related_type, related_id, id);

create index reviews_related_created_idx
  on public.reviews (related_type, related_id, created_at desc, id desc);

create index product_mobiles_product_id_idx
  on public.product_mobiles (product_id);
create index product_mobiles_mobile_id_idx
  on public.product_mobiles (mobile_id);

create index orders_user_id_idx
  on public.orders (user_id);

create index spec_groups_related_sort_idx
  on public.spec_groups (related_type, related_id, sort_order);
create index spec_group_items_group_sort_idx
  on public.spec_group_items (spec_group_id, sort_order);

create index product_feature_sections_related_sort_idx
  on public.product_feature_sections (
    related_type,
    related_id,
    active,
    sort_order
  );
create index product_feature_sections_feature_idx
  on public.product_feature_sections (
    related_type,
    related_id,
    feature_key,
    sort_order
  );
create index product_feature_slides_section_sort_idx
  on public.product_feature_slides (
    product_feature_section_id,
    active,
    sort_order
  );

-- Compact, RLS-aware read model for the side-by-side comparison UI.
create view public.comparison_items
with (security_invoker = true, security_barrier = true)
as
select
  'product:' || products.id::text as item_key,
  'product'::text as entity_type,
  products.id as entity_id,
  products.comparison_family,
  products.name,
  products.slug as handle,
  coalesce(products.short_description, products.description) as summary,
  products.price,
  null::numeric as original_price,
  null::smallint as warranty_years,
  null::integer as sort_priority,
  primary_image.url as image_url,
  coalesce(primary_image.alt_text, products.image_alt_text, products.name) as image_alt
from public.products
left join lateral (
  select images.url, images.alt_text
  from public.images
  where images.related_type = 'product'
    and images.related_id = products.id
  order by images.sort_order, images.id
  limit 1
) as primary_image on true
where products.comparison_family is not null

union all

select
  'mobile:' || mobiles.id::text as item_key,
  'mobile'::text as entity_type,
  mobiles.id as entity_id,
  mobiles.comparison_family,
  mobiles.name,
  mobiles.slug as handle,
  mobiles.description as summary,
  mobiles."Price"::numeric as price,
  mobiles.original_price::numeric,
  mobiles.warranty as warranty_years,
  mobiles.piority as sort_priority,
  primary_image.url as image_url,
  coalesce(primary_image.alt_text, mobiles.image_alt_text, mobiles.name) as image_alt
from public.mobiles
left join lateral (
  select images.url, images.alt_text
  from public.images
  where images.related_type = 'mobile'
    and images.related_id = mobiles.id
  order by images.sort_order, images.id
  limit 1
) as primary_image on true;

-- ---------------------------------------------------------------------------
-- Row Level Security
--
-- Catalog/content tables are readable through the Data API. No browser role
-- receives insert/update/delete privileges. Customer and order tables have RLS
-- enabled with no browser policies; the current application accesses them only
-- through server routes using the service role.
-- ---------------------------------------------------------------------------

alter table public.blogs enable row level security;
alter table public.categories enable row level security;
alter table public.category_relations enable row level security;
alter table public.colors enable row level security;
alter table public.faqs enable row level security;
alter table public.images enable row level security;
alter table public.mobiles enable row level security;
alter table public.orders enable row level security;
alter table public.product_feature_sections enable row level security;
alter table public.product_feature_slides enable row level security;
alter table public.product_mobiles enable row level security;
alter table public.products enable row level security;
alter table public.reviews enable row level security;
alter table public.spec_group_items enable row level security;
alter table public.spec_groups enable row level security;
alter table public.users enable row level security;

create policy blogs_public_read
  on public.blogs for select
  to anon, authenticated
  using (is_published is true);

create policy categories_public_read
  on public.categories for select
  to anon, authenticated
  using (true);

create policy category_relations_public_read
  on public.category_relations for select
  to anon, authenticated
  using (related_type in ('product', 'mobile'));

create policy colors_public_read
  on public.colors for select
  to anon, authenticated
  using (true);

create policy faqs_public_read
  on public.faqs for select
  to anon, authenticated
  using (
    related_type in ('product', 'mobile')
    or (
      related_type = 'blog'
      and exists (
        select 1
        from public.blogs
        where blogs.id = faqs.related_id
          and blogs.is_published is true
      )
    )
  );

create policy images_public_read
  on public.images for select
  to anon, authenticated
  using (
    related_type in ('product', 'mobile', 'detail_mobile', 'detail_product')
    or (
      related_type = 'blog'
      and exists (
        select 1
        from public.blogs
        where blogs.id = images.related_id
          and blogs.is_published is true
      )
    )
  );

create policy mobiles_public_read
  on public.mobiles for select
  to anon, authenticated
  using (true);

create policy product_feature_sections_public_read
  on public.product_feature_sections for select
  to anon, authenticated
  using (
    active is true
    and related_type in ('product', 'mobile')
  );

create policy product_feature_slides_public_read
  on public.product_feature_slides for select
  to anon, authenticated
  using (
    active is true
    and exists (
      select 1
      from public.product_feature_sections
      where product_feature_sections.id =
        product_feature_slides.product_feature_section_id
        and product_feature_sections.active is true
        and product_feature_sections.related_type in ('product', 'mobile')
    )
  );

create policy product_mobiles_public_read
  on public.product_mobiles for select
  to anon, authenticated
  using (true);

create policy products_public_read
  on public.products for select
  to anon, authenticated
  using (true);

create policy reviews_public_read
  on public.reviews for select
  to anon, authenticated
  using (related_type in ('product', 'mobile'));

create policy spec_group_items_public_read
  on public.spec_group_items for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.spec_groups
      where spec_groups.id = spec_group_items.spec_group_id
        and spec_groups.related_type in ('product', 'mobile')
    )
  );

create policy spec_groups_public_read
  on public.spec_groups for select
  to anon, authenticated
  using (related_type in ('product', 'mobile'));

-- Explicit Data API exposure. RLS still controls which rows are returned.
grant usage on schema public to anon, authenticated;

grant usage on type
  public.blog_content_type,
  public.order_status_enum,
  public.payment_status_enum,
  public.product_type_enum,
  public.related_type_enum
to anon, authenticated;

grant select on table
  public.blogs,
  public.categories,
  public.category_relations,
  public.colors,
  public.comparison_items,
  public.faqs,
  public.images,
  public.mobiles,
  public.product_feature_sections,
  public.product_feature_slides,
  public.product_mobiles,
  public.products,
  public.reviews,
  public.spec_group_items,
  public.spec_groups
to anon, authenticated;

revoke all on table public.orders, public.users from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

commit;

-- ---------------------------------------------------------------------------
-- Verification output
-- These read-only queries should return 5 enums and 16 tables with RLS enabled.
-- ---------------------------------------------------------------------------

select
  t.typname as enum_name,
  array_agg(e.enumlabel order by e.enumsortorder) as values
from pg_type as t
join pg_namespace as n on n.oid = t.typnamespace
join pg_enum as e on e.enumtypid = t.oid
where n.nspname = 'public'
  and t.typname in (
    'blog_content_type',
    'order_status_enum',
    'payment_status_enum',
    'product_type_enum',
    'related_type_enum'
  )
group by t.typname
order by t.typname;

select
  schemaname,
  tablename,
  rowsecurity
from pg_tables
where schemaname = 'public'
  and tablename in (
    'blogs',
    'categories',
    'category_relations',
    'colors',
    'faqs',
    'images',
    'mobiles',
    'orders',
    'product_feature_sections',
    'product_feature_slides',
    'product_mobiles',
    'products',
    'reviews',
    'spec_group_items',
    'spec_groups',
    'users'
  )
order by tablename;
